# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musev.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusev.proto\x12\x05musev\"\xe4\x01\n\x11Img2VideoInputMsg\x12\x17\n\x0f\x63onditionImages\x18\x01 \x01(\t\x12\x16\n\x0eipadapterImage\x18\x02 \x01(\t\x12\x12\n\nreferImage\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x12\n\nscaleRatio\x18\x05 \x01(\x02\x12\x17\n\x0f\x65yeBlinksFactor\x18\x06 \x01(\x02\x12\x0c\n\x04\x64\x65st\x18\x07 \x01(\t\x12\x0b\n\x03\x66ps\x18\x08 \x01(\x05\x12\x0e\n\x06length\x18\t \x01(\x05\x12\x13\n\x0bmotionSpeed\x18\n \x01(\x02\x12\r\n\x05\x62\x61tch\x18\x0b \x01(\x05\"s\n\x16Img2VideoAsyncInputMsg\x12\'\n\x05input\x18\x01 \x01(\x0b\x32\x18.musev.Img2VideoInputMsg\x12\x18\n\x10progressCallback\x18\x02 \x01(\t\x12\x16\n\x0e\x66inishCallback\x18\x03 \x01(\t\"1\n\x11Img2VideoResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t2\x95\x01\n\x05MuseV\x12@\n\x08Generate\x12\x18.musev.Img2VideoInputMsg\x1a\x18.musev.Img2VideoResponse\"\x00\x12J\n\rGenerateAsync\x12\x1d.musev.Img2VideoAsyncInputMsg\x1a\x18.musev.Img2VideoResponse\"\x00\x42\x63\n\x19\x63om.arkai.inference.musevB\x0cMuseVServiceP\x01Z.gitlab.in.promiseland.live/ark/ark-api/ai_grpc\xa2\x02\x05museVb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'musev_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.arkai.inference.musevB\014MuseVServiceP\001Z.gitlab.in.promiseland.live/ark/ark-api/ai_grpc\242\002\005museV'
  _globals['_IMG2VIDEOINPUTMSG']._serialized_start=23
  _globals['_IMG2VIDEOINPUTMSG']._serialized_end=251
  _globals['_IMG2VIDEOASYNCINPUTMSG']._serialized_start=253
  _globals['_IMG2VIDEOASYNCINPUTMSG']._serialized_end=368
  _globals['_IMG2VIDEORESPONSE']._serialized_start=370
  _globals['_IMG2VIDEORESPONSE']._serialized_end=419
  _globals['_MUSEV']._serialized_start=422
  _globals['_MUSEV']._serialized_end=571
# @@protoc_insertion_point(module_scope)
